$ANSIBLE_VAULT;1.1;AES256
37393432333039653133383763373831383361623431313066323437373531373161616262653136
3130333630663935636133313739623939336431316464310a396365363062633662366536333035
39363365653261346562306466323665353834393234373562373730303366383635666666323431
3531386462393632660a373865643734316138346130386565383730313735356662616538393265
62616566636563306333303636633965383235323137643437336164383137373964663233646136
66643832356636366332323237363536373038353132323237396133653932623731333437666436
34353834366331616433613763623664633164663733386335636162646462326434613666663261
35633037633664373862613732303034396437386531376665346332343065386666323465613232
62383633376162393132333338346536383961323439306338393465383332383336313937336234
34363564396466346334326166653435343937303837646536653932633832653363396565636236
38323238376261353862363065663834323233633839613161333864623762333638636538383136
30663166323935313462333164633632373464373664663763616639326139616462353961663738
34336233306230336233636332663562656165313561656531396430333561333930303630383330
37373530633465656365643838316638376466643530646238386636623034613065656238343332
383530373866653761383635373038363739
